[package]
name = "waycat"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
waybar-cffi = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
itertools = "0.14.0"
